### ISSUE TITLE
Can't install, error "INSTALL_FAILED_CONTAINER_ERROR"

### ISSUE THREAD

**Issue by utack** [cw/svg-viewer-android#21]
When installing on a  Xperia Z1 with Android 5.1.1(Cyanogenmod 12.1) it aborts with the error
"Failure [INSTALL_FAILED_CONTAINER_ERROR]"
Installing on Nexus 5 with with Cyanogenmod 12.1 fails.
Installing on Nexus 7 with Android 5.1.0 stock rom works.
Installing on a Xperia Z3 compact with Android 5.0 stock also works.

Apparently "android:installLocation="preferExternal"" causes this, and it can be fixed by setting it to android:installLocation="auto"", but the bug is Cyanogenmod specific, so feel free to mark this issue invalid.

**Comment by utack** [comment]
Thanks to razorloves for this solution:
"Settings - Apps, click on 3dot menu then Preferred install location"
It works when set to internal

**Comment by Lekensteyn** [comment]
This is definitely something specific to the CM12.1 modifications added after android-5.1.0_r3.

**Comment by Lekensteyn** [comment]
See http://review.cyanogenmod.org/97562
